title = "Default Article Title"
description = "A default description for the article."
body = "<p>This is the default <strong>HTML body</strong> content.</p><h2>Subtitle</h2><p>More content here.</p>"
createdAt = "2025-05-21T15:49:23.605Z"
publishedAt = "2025-05-28T15:49:23.605Z"
readingTime = 5
category = "General"

[image]
url = "https://placehold.co/600x400/EEE/31343C?text=Default+Image"
alt = "Default placeholder image"
caption = "This is a default image caption."

[[authors]]
name = "Dr. Default Author"
authorBio = "The default author of this article."
slug = "default-author"

[professor]
name = "Professor Default"
professorBio = "The default professor reviewing this article."
slug = "default-professor"

[[questions]]
question = "What is the default question?"
answers = [
    "Answer A",
    "Answer B (Correct)",
    "Answer C",
    "Answer D",
]
correct_answer = "Answer B (Correct)"

[[questions]]
question = "Is this another default question?"
answers = [
    "Yes (Correct)",
    "No",
    "Maybe",
]
correct_answer = "Yes (Correct)"
